/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeKitRouteImport } from './routes/le-kit'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const LeKitRoute = LeKitRouteImport.update({
  id: '/le-kit',
  path: '/le-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/le-kit': typeof LeKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/le-kit': typeof LeKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRoute
  '/le-kit': typeof LeKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/conseils'
    | '/contact'
    | '/engagements'
    | '/le-kit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/conseils' | '/contact' | '/engagements' | '/le-kit'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/conseils'
    | '/contact'
    | '/engagements'
    | '/le-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ConseilsRoute: typeof ConseilsRoute
  ContactRoute: typeof ContactRoute
  EngagementsRoute: typeof EngagementsRoute
  LeKitRoute: typeof LeKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/le-kit': {
      id: '/le-kit'
      path: '/le-kit'
      fullPath: '/le-kit'
      preLoaderRoute: typeof LeKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ConseilsRoute: ConseilsRoute,
  ContactRoute: ContactRoute,
  EngagementsRoute: EngagementsRoute,
  LeKitRoute: LeKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
